#!/usr/bin/env perl

use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/lib";
use SkyNet::Base;
use SkyNet::RPC;
use SkyNet::Server;

my $server   = SkyNet::Server->new(
                'db_username' => 'skynet',
                'db_password' => 'skynet2021',);

$server->listen_on_port(9765);
#$database->authenticate_user('Munny', 'bananafire35');
#$database->query("select * from users;");
$server->loop();

